export const orders = [
    {
        onOrderDetailsClick: (): void => undefined,
        onCustomersButtonClick: (): void => undefined,
        date: '111',
        menuName: '111',
        clientName: '111',
        clientImage: '',
        event: '111',
        eventDate: '111',
        persons: '111',
        time: '111',
        address: '111',
    },
    {
        onOrderDetailsClick: (): void => undefined,
        onCustomersButtonClick: (): void => undefined,
        date: '111',
        menuName: '111',
        clientName: '111',
        clientImage: '',
        event: '111',
        eventDate: '111',
        persons: '111',
        time: '111',
        address: '111',
    },
    {
        onOrderDetailsClick: (): void => undefined,
        onCustomersButtonClick: (): void => undefined,
        date: '111',
        menuName: '111',
        clientName: '111',
        clientImage: '',
        event: '111',
        eventDate: '111',
        persons: '111',
        time: '111',
        address: '111',
    },
];
