name: Production Pull Request

on:
  workflow_dispatch:

jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: integration
          title: 'Integration -> Production'
          body: ''
          delete-branch: false
          draft: false
